# Generated by Django 6.1.1 on 2026-09-24 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(choices=[('rossmann', 'Rossmann'), ('doz', 'DOZ'), ('superpharm', 'Super-Pharm'), ('gemini', 'Gemini')], max_length=16)),
                ('url', models.URLField(max_length=2048)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_pages', to='prices.product')),
            ],
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observed_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('shop_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='prices.shoppage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shoppage',
            constraint=models.UniqueConstraint(fields=('product', 'shop'), name='prices_shoppage_unique_product_shop'),
        ),
    ]
