# Generated by Django 6.1.1 on 2026-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='prices_priceobservation_amount_positive'),
        ),
    ]
